development:
    sessions:
      default:
        database: confapp_development
        hosts:
          - localhost:27017

    options:
      include_root_in_json: true

# set these environment variables on your prod server

production:
 uri: <%= ENV['MONGOHQ_URL'] %>

 #uri: <%= ENV['MONGOHQ_URL'] %>

#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>



  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019