development:
    sessions:
      default:
        database: confapp_development
        hosts:
          - localhost:27017

    options:
      include_root_in_json: true

# set these environment variables on your prod server

production:
    sessions:
      default:
        uri: <%= ENV['MONGOHQ_URL'] %>
        options:
          skip_version_check: true
          include_root_in_json: true
          safe: true